<form method="post" action="forms" data-oa data-oa-target="#result" data-oa-scroll data-oa-history data-oa-callback="myCallback">
	<input type="hidden" name="action" value="callback">
	<input type="submit" value="Send" class="btn btn-primary">
</form>
<script>
function myCallback() {
	document.getElementById('result').insertAdjacentHTML('afterbegin', '<div class="alert alert-info">This alert is generated by the *data-oa-callback* fuction</div>')
}
</script>